//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIndividual.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AE_ESCALAS_VUELOS
    {
        public int id { get; set; }
        public int cod_vuelo { get; set; }
        public int cod_pais { get; set; }
        public string duracion_escala { get; set; }
        public Nullable<System.DateTime> fec_vuelo { get; set; }
        public string ind_estado { get; set; }
    
        public virtual AE_PAISES AE_PAISES { get; set; }
        public virtual AE_VUELOS AE_VUELOS { get; set; }
    }
}
