//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIndividual.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AE_PAGO_BOLETO
    {
        public int id { get; set; }
        public int comprobante { get; set; }
        public int cod_reserva { get; set; }
        public Nullable<decimal> monto_boleto { get; set; }
        public Nullable<int> impuesto { get; set; }
        public string ind_estado { get; set; }
    
        public virtual AE_RESERVA_BOLETO AE_RESERVA_BOLETO { get; set; }
    }
}
