//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIndividual.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AE_PAISES
    {
        public AE_PAISES()
        {
            this.AE_ESCALAS_VUELOS = new HashSet<AE_ESCALAS_VUELOS>();
            this.AE_VUELOS = new HashSet<AE_VUELOS>();
            this.AE_VUELOS1 = new HashSet<AE_VUELOS>();
        }
    
        public int id { get; set; }
        public string desc_pais { get; set; }
        public string ind_estado { get; set; }
    
        public virtual ICollection<AE_ESCALAS_VUELOS> AE_ESCALAS_VUELOS { get; set; }
        public virtual ICollection<AE_VUELOS> AE_VUELOS { get; set; }
        public virtual ICollection<AE_VUELOS> AE_VUELOS1 { get; set; }
    }
}
