//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIndividual.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AE_PASAJEROS
    {
        public AE_PASAJEROS()
        {
            this.AE_RESERVA_BOLETO = new HashSet<AE_RESERVA_BOLETO>();
        }
    
        public int id { get; set; }
        public string identificacion { get; set; }
        public string nombre { get; set; }
        public Nullable<int> pasaporte { get; set; }
        public Nullable<int> visa { get; set; }
        public Nullable<System.DateTime> fec_nacimiento { get; set; }
        public string correo_electronico { get; set; }
        public Nullable<int> telefono { get; set; }
        public Nullable<int> cod_estado { get; set; }
    
        public virtual ICollection<AE_RESERVA_BOLETO> AE_RESERVA_BOLETO { get; set; }
    }
}
