//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIndividual.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AE_RESERVA_BOLETO
    {
        public AE_RESERVA_BOLETO()
        {
            this.AE_PAGO_BOLETO = new HashSet<AE_PAGO_BOLETO>();
        }
    
        public int id { get; set; }
        public int cod_boleto { get; set; }
        public int cod_pasajero { get; set; }
        public int cod_clase { get; set; }
        public string num_asiento { get; set; }
        public string ind_estado { get; set; }
    
        public virtual AE_BOLETOS_AVION AE_BOLETOS_AVION { get; set; }
        public virtual AE_CLASE AE_CLASE { get; set; }
        public virtual ICollection<AE_PAGO_BOLETO> AE_PAGO_BOLETO { get; set; }
        public virtual AE_PASAJEROS AE_PASAJEROS { get; set; }
    }
}
