//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIndividual.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AE_VUELOS
    {
        public AE_VUELOS()
        {
            this.AE_BOLETOS_AVION = new HashSet<AE_BOLETOS_AVION>();
            this.AE_ESCALAS_VUELOS = new HashSet<AE_ESCALAS_VUELOS>();
        }
    
        public int id { get; set; }
        public int cod_compania { get; set; }
        public int cod_pais_abordaje { get; set; }
        public int cod_pais_destino { get; set; }
        public int cod_avion { get; set; }
        public string duracion { get; set; }
        public Nullable<System.DateTime> fec_vuelo { get; set; }
        public Nullable<System.DateTime> fec_salida { get; set; }
        public Nullable<System.DateTime> fec_entrada { get; set; }
        public string ind_estado { get; set; }
    
        public virtual ICollection<AE_BOLETOS_AVION> AE_BOLETOS_AVION { get; set; }
        public virtual AE_COMPANIA AE_COMPANIA { get; set; }
        public virtual ICollection<AE_ESCALAS_VUELOS> AE_ESCALAS_VUELOS { get; set; }
        public virtual AE_PAISES AE_PAISES { get; set; }
        public virtual AE_PAISES AE_PAISES1 { get; set; }
        public virtual AE_TIPOS_AVIONES AE_TIPOS_AVIONES { get; set; }
    }
}
