//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIndividual.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AeropuertoEntities : DbContext
    {
        public AeropuertoEntities()
            : base("name=AeropuertoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AE_BOLETOS_AVION> AE_BOLETOS_AVION { get; set; }
        public DbSet<AE_CLASE> AE_CLASE { get; set; }
        public DbSet<AE_COMPANIA> AE_COMPANIA { get; set; }
        public DbSet<AE_ESCALAS_VUELOS> AE_ESCALAS_VUELOS { get; set; }
        public DbSet<AE_PAGO_BOLETO> AE_PAGO_BOLETO { get; set; }
        public DbSet<AE_PAISES> AE_PAISES { get; set; }
        public DbSet<AE_PASAJEROS> AE_PASAJEROS { get; set; }
        public DbSet<AE_RESERVA_BOLETO> AE_RESERVA_BOLETO { get; set; }
        public DbSet<AE_TIPOS_AVIONES> AE_TIPOS_AVIONES { get; set; }
        public DbSet<AE_VUELOS> AE_VUELOS { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
